In [1]:
import pandas as pd
import sys
sys.path.append('../..')
import sla

**Log de tipo WAS**

In [4]:
from sla.ingestion.ingestor import LogIngestor

df_was = LogIngestor.ingest("data/WAS.log", "WAS")
df_was.head()

,timestamp,log_level,service,transaction_id,account_from,account_to,amount,response_code,trama_rq,trama_uuid,trama_rs,process_transaction,connection_group
0,2023-01-04 23:57:35.514,INFO,co.com.grporg.bancolombia.entappfwtx85.templat...,725046037527929,912-452207-37,07457018520,11000.00,000,8625595062610538000001113700620100000000000000...,104aaafc0a08021f7966534b04d74e8b,8625595062610538000001113700620100000000000000...,0538,TRANSFER
1,2023-01-04 23:57:35.583,INFO,co.com.grporg.bancolombia.entappfwtx85.templat...,637649593876045,455-727374-58,3157298434,30500.00,000,86255950624116380000000551621801 ...,104aaaba0a08021fa6aa598e04d74e89,86255950624116380000000551621801 ...,1638,TRANSFER_NEQUI
2,2023-01-04 23:57:35.781,INFO,co.com.grporg.bancolombia.entappfwtx85.templat...,886843242555050,869-182784-37,3138738895,60000.00,000,86255950628116380000000142446431 ...,104aab180a08021fa5b5d9f504d74e8d,86255950628116380000000142446431 ...,1638,TRANSFER_NEQUI
3,2023-01-04 23:57:35.983,INFO,co.com.grporg.bancolombia.entappfwtx85.templat...,770649094820318,486-450966-09,3022966820,7000.00,000,86255950636116380000000087162951 ...,104aac370a08021f848652cc04d74e95,86255950636116380000000087162951 ...,1638,TRANSFER_NEQUI
4,2023-01-04 23:57:36.228,INFO,co.com.grporg.bancolombia.entappfwtx85.templat...,315226094637424,71807047056,None,None,000,86256950645108880000011105092341 ...,104aaed70a08021f5bf5bf8604d74e9e,86256950645108880000011105092341 ...,0888,SIMPLI_5

**Log de HDC**

In [5]:
df_hdc = LogIngestor.ingest("data/HDC_1.log", "HDC")
df_hdc.head()

,timestamp,thread_id,log_source,log_type,message,error_code
0,15/03/24 12:35:09:695,00000220,SystemOut,O,12:35:09.695 [WebContainer : 22] ERROR co.com....,None
1,15/03/24 12:35:09:714,00000220,SystemOut,O,12:35:09.714 [WebContainer : 22] ERROR co.com....,None
2,15/03/24 12:35:09:714,00000220,SystemOut,O,12:35:09.714 [WebContainer : 22] ERROR co.com....,None
3,15/03/24 12:35:09:714,00000220,SystemOut,O,12:35:09.714 [WebContainer : 22] ERROR co.com....,None
4,15/03/24 12:35:09:716,00000220,SystemOut,O,12:35:09.716 [WebContainer : 22] ERROR co.com....,None

**Log de HSM**

In [ ]:
df_hsm = LogIngestor.ingest("data/HSM.log", "HSM")
df_hsm.head()

,date,time,level,ip,category,message
0,2024 Nov 1,17:00:01,notice,10.2.2.20,System,Log rotation: Successfully rotated System Log.
1,2024 Nov 1,17:04:53,notice,10.2.2.20,ACS,11/01/2024 17:04:54.00 - Performing on-demand ...
2,2024 Nov 1,17:04:53,debug,10.2.2.20,SNMP Agent,SNMP is not running. Trap requested but not sent.
3,2024 Nov 1,17:04:53,notice,10.2.2.20,ACS,11/01/2024 17:04:54.00 - on-demand self-tests ...
4,2024 Nov 1,17:04:53,debug,10.2.2.20,SNMP Agent,SNMP is not running. Trap requested but not sent.

**Log de IBM MQ**

In [8]:
df_ibm = LogIngestor.ingest("data/IBM_MQ.txt", "IBM_MQ")
df_ibm.head()

,Process,Program,Host,Installation,VRMF,QMgr,Time,RemoteHost,ArithInsert,CommentInsert1,CommentInsert2,CommentInsert3,CodigoAMQ_Error,DescripcionCodigoAMQ_Error,Explanation,Action
0,2323.10269,amqrmppa,ip-10-103-75-18.ec2.internal,Installation1,9.3.0.10,PAWSQMGRFRFUA02,2024-02-06T23:00:03.284Z,::1,420,????,gsk_secure_soc_read,localhost (::1,AMQ9665E,SSL connection closed by remote end of channel...,6/02/2024 18:00:03\t1.70726E+12\tThe SSL or TL...,6/02/2024 18:00:03\t1.70726E+12\tCheck the rem...
1,2323.10269,amqrmppa,ip-10-103-75-18.ec2.internal,Installation1,9.3.0.10,PAWSQMGRFRFUA02,2024-02-06T23:00:03.284Z,,,????,2323,localhost (::1,AMQ9999E,Channel '????' to host 'localhost (::1)' ended...,6/02/2024 18:00:03\t1.70726E+12\tThe channel p...,6/02/2024 18:00:03\t1.70726E+12\tLook at previ...
2,2323.10270,amqrmppa,ip-10-103-75-18.ec2.internal,Installation1,9.3.0.10,PAWSQMGRFRFUA02,2024-02-07T11:00:03.397Z,::1,420,????,gsk_secure_soc_read,localhost (::1,AMQ9665E,SSL connection closed by remote end of channel...,7/02/2024 6:00:04\t1.7073E+12\tThe SSL or TLS ...,7/02/2024 6:00:04\t1.7073E+12\tCheck the remot...
3,2323.10270,amqrmppa,ip-10-103-75-18.ec2.internal,Installation1,9.3.0.10,PAWSQMGRFRFUA02,2024-02-07T11:00:03.397Z,,,????,2323,localhost (::1,AMQ9999E,Channel '????' to host 'localhost (::1)' ended...,7/02/2024 6:00:04\t1.7073E+12\tThe channel pro...,7/02/2024 6:00:04\t1.7073E+12\tLook at previou...
4,2323.10271,amqrmppa,ip-10-103-75-18.ec2.internal,Installation1,9.3.0.10,PAWSQMGRFRFUA02,2024-02-07T23:00:02.808Z,::1,420,????,gsk_secure_soc_read,localhost (::1,AMQ9665E,SSL connection closed by remote end of channel...,7/02/2024 18:00:03\t1.70735E+12\tThe SSL or TL...,7/02/2024 18:00:03\t1.70735E+12\tCheck the rem...